# Generated by Django 5.1.3 on 2024-11-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0002_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
