# Generated by Django 5.1.3 on 2024-12-04 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0007_alter_report_date_of_report_card_generation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="user",
        ),
    ]
