# Generated by Django 5.1.3 on 2024-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0010_recipe_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
