# Generated by Django 5.1.3 on 2024-12-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0013_recipe_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
