# Generated by Django 5.1.3 on 2024-12-06 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0014_remove_recipe_is_deleted_student_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="is_deleted",
        ),
    ]
